// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// drb_blas_check
double drb_blas_check(const arma::mat& a, const arma::mat& b);
RcppExport SEXP _DRBayes_drb_blas_check(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(drb_blas_check(a, b));
    return rcpp_result_gen;
END_RCPP
}
// drb_mean_one_pass
double drb_mean_one_pass(const Rcpp::NumericVector& x, bool wide);
RcppExport SEXP _DRBayes_drb_mean_one_pass(SEXP xSEXP, SEXP wideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type wide(wideSEXP);
    rcpp_result_gen = Rcpp::wrap(drb_mean_one_pass(x, wide));
    return rcpp_result_gen;
END_RCPP
}
// drb_mean_two_pass
double drb_mean_two_pass(const Rcpp::NumericVector& x, bool wide);
RcppExport SEXP _DRBayes_drb_mean_two_pass(SEXP xSEXP, SEXP wideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type wide(wideSEXP);
    rcpp_result_gen = Rcpp::wrap(drb_mean_two_pass(x, wide));
    return rcpp_result_gen;
END_RCPP
}
// drb_row_means
Rcpp::NumericVector drb_row_means(const Rcpp::NumericMatrix& x, int block, bool wide);
RcppExport SEXP _DRBayes_drb_row_means(SEXP xSEXP, SEXP blockSEXP, SEXP wideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type block(blockSEXP);
    Rcpp::traits::input_parameter< bool >::type wide(wideSEXP);
    rcpp_result_gen = Rcpp::wrap(drb_row_means(x, block, wide));
    return rcpp_result_gen;
END_RCPP
}
// drb_range
Rcpp::NumericVector drb_range(const Rcpp::NumericVector& x);
RcppExport SEXP _DRBayes_drb_range(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(drb_range(x));
    return rcpp_result_gen;
END_RCPP
}
// drb_inverse_link
Rcpp::NumericVector drb_inverse_link(Rcpp::NumericVector x, int code);
RcppExport SEXP _DRBayes_drb_inverse_link(SEXP xSEXP, SEXP codeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type code(codeSEXP);
    rcpp_result_gen = Rcpp::wrap(drb_inverse_link(x, code));
    return rcpp_result_gen;
END_RCPP
}
// drb_ipw_weight
Rcpp::NumericVector drb_ipw_weight(Rcpp::NumericVector eta, const Rcpp::NumericVector& a, int ps_link);
RcppExport SEXP _DRBayes_drb_ipw_weight(SEXP etaSEXP, SEXP aSEXP, SEXP ps_linkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type ps_link(ps_linkSEXP);
    rcpp_result_gen = Rcpp::wrap(drb_ipw_weight(eta, a, ps_link));
    return rcpp_result_gen;
END_RCPP
}
// drb_moment_ipw
Rcpp::List drb_moment_ipw(const Rcpp::NumericMatrix& Z_ps, const Rcpp::NumericMatrix& Z_lm, const Rcpp::NumericVector& A, const Rcpp::NumericVector& Y, const Rcpp::NumericMatrix& betas_ps, const Rcpp::NumericMatrix& betas_otc, int ps_link, int otc_link, double max_cells, bool wide);
RcppExport SEXP _DRBayes_drb_moment_ipw(SEXP Z_psSEXP, SEXP Z_lmSEXP, SEXP ASEXP, SEXP YSEXP, SEXP betas_psSEXP, SEXP betas_otcSEXP, SEXP ps_linkSEXP, SEXP otc_linkSEXP, SEXP max_cellsSEXP, SEXP wideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Z_ps(Z_psSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Z_lm(Z_lmSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type betas_ps(betas_psSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type betas_otc(betas_otcSEXP);
    Rcpp::traits::input_parameter< int >::type ps_link(ps_linkSEXP);
    Rcpp::traits::input_parameter< int >::type otc_link(otc_linkSEXP);
    Rcpp::traits::input_parameter< double >::type max_cells(max_cellsSEXP);
    Rcpp::traits::input_parameter< bool >::type wide(wideSEXP);
    rcpp_result_gen = Rcpp::wrap(drb_moment_ipw(Z_ps, Z_lm, A, Y, betas_ps, betas_otc, ps_link, otc_link, max_cells, wide));
    return rcpp_result_gen;
END_RCPP
}
// drb_moment_subclass
Rcpp::NumericVector drb_moment_subclass(const Rcpp::NumericMatrix& Z_lm, const Rcpp::NumericVector& Y, const Rcpp::NumericVector& w, const Rcpp::NumericMatrix& betas_otc, int otc_link, double max_cells, bool wide);
RcppExport SEXP _DRBayes_drb_moment_subclass(SEXP Z_lmSEXP, SEXP YSEXP, SEXP wSEXP, SEXP betas_otcSEXP, SEXP otc_linkSEXP, SEXP max_cellsSEXP, SEXP wideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Z_lm(Z_lmSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type betas_otc(betas_otcSEXP);
    Rcpp::traits::input_parameter< int >::type otc_link(otc_linkSEXP);
    Rcpp::traits::input_parameter< double >::type max_cells(max_cellsSEXP);
    Rcpp::traits::input_parameter< bool >::type wide(wideSEXP);
    rcpp_result_gen = Rcpp::wrap(drb_moment_subclass(Z_lm, Y, w, betas_otc, otc_link, max_cells, wide));
    return rcpp_result_gen;
END_RCPP
}
// drb_ps_rowmeans
Rcpp::List drb_ps_rowmeans(const Rcpp::NumericMatrix& Z_ps, const Rcpp::NumericMatrix& betas_ps, int ps_link, double max_cells, bool wide);
RcppExport SEXP _DRBayes_drb_ps_rowmeans(SEXP Z_psSEXP, SEXP betas_psSEXP, SEXP ps_linkSEXP, SEXP max_cellsSEXP, SEXP wideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Z_ps(Z_psSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type betas_ps(betas_psSEXP);
    Rcpp::traits::input_parameter< int >::type ps_link(ps_linkSEXP);
    Rcpp::traits::input_parameter< double >::type max_cells(max_cellsSEXP);
    Rcpp::traits::input_parameter< bool >::type wide(wideSEXP);
    rcpp_result_gen = Rcpp::wrap(drb_ps_rowmeans(Z_ps, betas_ps, ps_link, max_cells, wide));
    return rcpp_result_gen;
END_RCPP
}
// drb_moment_np_ipw
Rcpp::List drb_moment_np_ipw(const Rcpp::NumericMatrix& Z_ps, const Rcpp::NumericVector& A, const Rcpp::NumericVector& Y, const Rcpp::NumericMatrix& mu, const Rcpp::NumericMatrix& betas_ps, int ps_link, bool wide);
RcppExport SEXP _DRBayes_drb_moment_np_ipw(SEXP Z_psSEXP, SEXP ASEXP, SEXP YSEXP, SEXP muSEXP, SEXP betas_psSEXP, SEXP ps_linkSEXP, SEXP wideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Z_ps(Z_psSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type betas_ps(betas_psSEXP);
    Rcpp::traits::input_parameter< int >::type ps_link(ps_linkSEXP);
    Rcpp::traits::input_parameter< bool >::type wide(wideSEXP);
    rcpp_result_gen = Rcpp::wrap(drb_moment_np_ipw(Z_ps, A, Y, mu, betas_ps, ps_link, wide));
    return rcpp_result_gen;
END_RCPP
}
// drb_moment_np_subclass
Rcpp::NumericVector drb_moment_np_subclass(const Rcpp::NumericVector& Y, const Rcpp::NumericMatrix& mu, const Rcpp::NumericVector& w, bool wide);
RcppExport SEXP _DRBayes_drb_moment_np_subclass(SEXP YSEXP, SEXP muSEXP, SEXP wSEXP, SEXP wideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type w(wSEXP);
    Rcpp::traits::input_parameter< bool >::type wide(wideSEXP);
    rcpp_result_gen = Rcpp::wrap(drb_moment_np_subclass(Y, mu, w, wide));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DRBayes_drb_blas_check", (DL_FUNC) &_DRBayes_drb_blas_check, 2},
    {"_DRBayes_drb_mean_one_pass", (DL_FUNC) &_DRBayes_drb_mean_one_pass, 2},
    {"_DRBayes_drb_mean_two_pass", (DL_FUNC) &_DRBayes_drb_mean_two_pass, 2},
    {"_DRBayes_drb_row_means", (DL_FUNC) &_DRBayes_drb_row_means, 3},
    {"_DRBayes_drb_range", (DL_FUNC) &_DRBayes_drb_range, 1},
    {"_DRBayes_drb_inverse_link", (DL_FUNC) &_DRBayes_drb_inverse_link, 2},
    {"_DRBayes_drb_ipw_weight", (DL_FUNC) &_DRBayes_drb_ipw_weight, 3},
    {"_DRBayes_drb_moment_ipw", (DL_FUNC) &_DRBayes_drb_moment_ipw, 10},
    {"_DRBayes_drb_moment_subclass", (DL_FUNC) &_DRBayes_drb_moment_subclass, 7},
    {"_DRBayes_drb_ps_rowmeans", (DL_FUNC) &_DRBayes_drb_ps_rowmeans, 5},
    {"_DRBayes_drb_moment_np_ipw", (DL_FUNC) &_DRBayes_drb_moment_np_ipw, 7},
    {"_DRBayes_drb_moment_np_subclass", (DL_FUNC) &_DRBayes_drb_moment_np_subclass, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_DRBayes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
