# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

drb_blas_check <- function(a, b) {
    .Call(`_DRBayes_drb_blas_check`, a, b)
}

drb_mean_one_pass <- function(x, wide) {
    .Call(`_DRBayes_drb_mean_one_pass`, x, wide)
}

drb_mean_two_pass <- function(x, wide) {
    .Call(`_DRBayes_drb_mean_two_pass`, x, wide)
}

drb_row_means <- function(x, block, wide) {
    .Call(`_DRBayes_drb_row_means`, x, block, wide)
}

drb_range <- function(x) {
    .Call(`_DRBayes_drb_range`, x)
}

drb_inverse_link <- function(x, code) {
    .Call(`_DRBayes_drb_inverse_link`, x, code)
}

drb_ipw_weight <- function(eta, a, ps_link) {
    .Call(`_DRBayes_drb_ipw_weight`, eta, a, ps_link)
}

#' The moment condition of equation (3.4)
#'
#' Two matrix products per block go to the same BLAS R would have used, and
#' everything after them is done in place: the fitted means are overwritten by
#' the inverse link, each weight is formed at the observation it multiplies,
#' and the residual, the product and the column sum never exist as matrices at
#' all. That is where the time goes -- the arithmetic is the same arithmetic,
#' but R forms about seven draws-by-observations matrices per block where this
#' holds two buffers.
#'
#' The positivity guard is not applied here. The extremes of the linear
#' predictor are returned instead, and R raises the error, so that its wording
#' lives in one place and no C++ exception has to travel through it.
#'
#' @return A list with `BB`, one value per draw, and `eta_range`, the smallest
#'   and largest linear predictor seen, or a zero-length vector when there were
#'   no draws to see one in.
#'
#' The accumulator width is settled once, on entry, from what R reports about
#' its own build; see the note at the top of reduce.h.
#'
#' @keywords internal
#' @noRd
drb_moment_ipw <- function(Z_ps, Z_lm, A, Y, betas_ps, betas_otc, ps_link, otc_link, max_cells, wide) {
    .Call(`_DRBayes_drb_moment_ipw`, Z_ps, Z_lm, A, Y, betas_ps, betas_otc, ps_link, otc_link, max_cells, wide)
}

#' The subclassification moment condition of equation (F.2)
#'
#' The stratum treated fraction is empirical and fixed before the sweep starts,
#' so this path never evaluates a propensity score: one matrix product rather
#' than two, and no positivity guard to reach. Neither the propensity score
#' design matrix nor its draws appear in the signature, which makes that a
#' property of the interface rather than a branch someone could later add.
#'
#' @return One value per draw, sized from the outcome draws.
#'
#' The accumulator width is settled once, on entry, from what R reports about
#' its own build; see the note at the top of reduce.h.
#'
#' @keywords internal
#' @noRd
drb_moment_subclass <- function(Z_lm, Y, w, betas_otc, otc_link, max_cells, wide) {
    .Call(`_DRBayes_drb_moment_subclass`, Z_lm, Y, w, betas_otc, otc_link, max_cells, wide)
}

#' Mean propensity score per observation, over the draws
#'
#' The strata of Appendix F are cut on this, and it was the largest single
#' allocation in the package: the linear predictors and the scores were both
#' held at full draws-by-observations size at once, 244 MB at two thousand
#' observations and eight thousand draws, to produce a vector of length n.
#' Accumulating across blocks rather than averaging block means keeps the
#' answer the one an unblocked pass would have given, bit for bit.
#'
#' @return A list with `ps_mean`, one value per observation, and `eta_range`.
#'
#' The accumulator width is settled once, on entry, from what R reports about
#' its own build; see the note at the top of reduce.h.
#'
#' @keywords internal
#' @noRd
drb_ps_rowmeans <- function(Z_ps, betas_ps, ps_link, max_cells, wide) {
    .Call(`_DRBayes_drb_ps_rowmeans`, Z_ps, betas_ps, ps_link, max_cells, wide)
}

#' The moment condition from supplied draws of the fitted outcome mean
#'
#' The fitted means arrive as draws by observations, the transpose of every
#' other matrix here, and are read one draw at a time. That is deliberate: R
#' forms each draw's linear predictor with a matrix-vector product, and
#' gathering the draws into a matrix product instead would be a different BLAS
#' kernel accumulating in a different order, moving the last bits for no gain,
#' since this is evaluated once per fit rather than once per sweep step.
#'
#' The reduction is the two-pass one, because R reaches this path through
#' mean() rather than colMeans().
#'
#' @return A list with `BB`, one value per draw, and `eta_range`.
#'
#' The accumulator width is settled once, on entry, from what R reports about
#' its own build; see the note at the top of reduce.h.
#'
#' @keywords internal
#' @noRd
drb_moment_np_ipw <- function(Z_ps, A, Y, mu, betas_ps, ps_link, wide) {
    .Call(`_DRBayes_drb_moment_np_ipw`, Z_ps, A, Y, mu, betas_ps, ps_link, wide)
}

#' The same, when the stratum weights of Appendix F stand in for the score
#'
#' No propensity score is formed at all, so there is no linear predictor and no
#' guard, and the weights are the same vector at every draw.
#'
#' @return One value per row of fitted means.
#'
#' The accumulator width is settled once, on entry, from what R reports about
#' its own build; see the note at the top of reduce.h.
#'
#' @keywords internal
#' @noRd
drb_moment_np_subclass <- function(Y, mu, w, wide) {
    .Call(`_DRBayes_drb_moment_np_subclass`, Y, mu, w, wide)
}

